version: '3'
services:
  app:
    build: ./docker/php
    container_name: workspace_app
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.17
    container_name: workspace_nginx
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/workspace.local.conf:/etc/nginx/conf.d/workspace.local.conf
    depends_on:
      - app
